name: backtest

on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  example-3:
    name: Backtest current strategy
    runs-on: "windows-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: prosperity
          environment-file: environment.yml
          python-version: 3.12
          auto-activate-base: false
      - run: |
          conda info
          conda list
