name: backtest

on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  example-3:
    name: Backtest current strategy
    runs-on: "windows-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      # - name: Cache conda
      #   uses: actions/cache@v3
      #   env:
      #     # Increase this value to reset cache if etc/example-environment.yml has not changed
      #     CACHE_NUMBER: 0
      #   with:
      #     path: ~/conda_pkgs_dir
      #     key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
      #       hashFiles('etc/example-environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: prosperity
          environment-file: environment.yml
          python-version: 3.12
          auto-activate-base: false
      - run: |
          conda info
          conda list
      - run: |
          python backtest.py
      - name: Upload failed tests
        uses: edunad/actions-image@v2.0.0
        with:
          path: "./plots/*.png"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          title: "Post backtest plots"
